---
run_mode: "load_data"
data_import_parameters:
  # specify if all data is too be scraped (all episodes, all ranks) (options: all, single)
  data_spec: "all"

  # specify episode and act to import data for
  episode: 6
  act: 2

  # specify which competitive rank (unrated = 0, plat 2 = 16, iron 1 = 3)
  rank: 25

  # specify which data set to import (Maps, Agents, Weapons, general, Agent_Map)
  dataset: "Agent_Map"

  # bounds for episodes and ranks on website
  min_rank: 3
  max_rank: 27
  min_episode: 2
  max_episode: 6
  min_act: 1
  max_act: 3
