---
runmode: "load_data"
data_import_parameters:
  # specify episode and act to import data for
  episode: 5
  act: 3
  # specify which competitive rank (unrated = 0, plat 2 = 16)
  rank: 17
  # specify which data set to import
  dataset: 'all'
